name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up Node
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20

      - name: Build and Test
        run: npm install && npm run build

      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          # Username used to log against the Docker registry
          username: "${{ secrets.DOCKER_USER }}"
          # Password or personal access token used to log against the Docker registry
          password: "${{ secrets.DOCKER_PASSWORD }}"

      - name: Build Docker image
        run: docker build -t djajcevic/sander-cool-app2-frontend:${{ github.sha }} .

      - name: Push Docker image to internal registry
        run: |
          docker tag djajcevic/sander-cool-app2-frontend:${{ github.sha }} djajcevic/sander-cool-app2-frontend:latest
          docker push djajcevic/sander-cool-app2-frontend:${{ github.sha }}
          docker push djajcevic/sander-cool-app2-frontend